//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.25 at 10:03:57 PM CST 
//


package ca.ieso.reports.schema.uplift;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DeliveryDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="HourlyUplift" maxOccurs="24">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DeliveryHour" type="{http://www.ieso.ca/schema}Hour1To24"/>
 *                   &lt;element name="Uplift" type="{http://www.ieso.ca/schema}Money"/>
 *                   &lt;element name="IOG" type="{http://www.ieso.ca/schema}Money"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deliveryDate",
    "hourlyUplift"
})
@XmlRootElement(name = "DocBody")
public class DocBody {

    @XmlElement(name = "DeliveryDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar deliveryDate;
    @XmlElement(name = "HourlyUplift", required = true)
    protected List<DocBody.HourlyUplift> hourlyUplift;

    /**
     * Gets the value of the deliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * Sets the value of the deliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeliveryDate(XMLGregorianCalendar value) {
        this.deliveryDate = value;
    }

    /**
     * Gets the value of the hourlyUplift property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the hourlyUplift property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getHourlyUplift().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocBody.HourlyUplift }
     * 
     * 
     */
    public List<DocBody.HourlyUplift> getHourlyUplift() {
        if (hourlyUplift == null) {
            hourlyUplift = new ArrayList<DocBody.HourlyUplift>();
        }
        return this.hourlyUplift;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DeliveryHour" type="{http://www.ieso.ca/schema}Hour1To24"/>
     *         &lt;element name="Uplift" type="{http://www.ieso.ca/schema}Money"/>
     *         &lt;element name="IOG" type="{http://www.ieso.ca/schema}Money"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "deliveryHour",
        "uplift",
        "iog"
    })
    public static class HourlyUplift {

        @XmlElement(name = "DeliveryHour")
        protected int deliveryHour;
        @XmlElement(name = "Uplift", required = true)
        protected BigDecimal uplift;
        @XmlElement(name = "IOG", required = true)
        protected BigDecimal iog;

        /**
         * Gets the value of the deliveryHour property.
         * 
         */
        public int getDeliveryHour() {
            return deliveryHour;
        }

        /**
         * Sets the value of the deliveryHour property.
         * 
         */
        public void setDeliveryHour(int value) {
            this.deliveryHour = value;
        }

        /**
         * Gets the value of the uplift property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getUplift() {
            return uplift;
        }

        /**
         * Sets the value of the uplift property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setUplift(BigDecimal value) {
            this.uplift = value;
        }

        /**
         * Gets the value of the iog property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getIOG() {
            return iog;
        }

        /**
         * Sets the value of the iog property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setIOG(BigDecimal value) {
            this.iog = value;
        }

    }

}
