//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.20 at 08:19:14 PM EST 
//


package ca.ieso.reports.schema.daadequacy;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ca.ieso.reports.schema.daadequacy package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DocConfClass_QNAME = new QName("http://www.ieso.ca/schema", "DocConfClass");
    private final static QName _CreatedAt_QNAME = new QName("http://www.ieso.ca/schema", "CreatedAt");
    private final static QName _DocTitle_QNAME = new QName("http://www.ieso.ca/schema", "DocTitle");
    private final static QName _DocRevision_QNAME = new QName("http://www.ieso.ca/schema", "DocRevision");
    private final static QName _DocConfGroup_QNAME = new QName("http://www.ieso.ca/schema", "DocConfGroup");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ca.ieso.reports.schema.daadequacy
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DocBody }
     * 
     */
    public DocBody createDocBody() {
        return new DocBody();
    }

    /**
     * Create an instance of {@link DocBody.System }
     * 
     */
    public DocBody.System createDocBodySystem() {
        return new DocBody.System();
    }

    /**
     * Create an instance of {@link DocBody.System.IntertieZonalEnergies }
     * 
     */
    public DocBody.System.IntertieZonalEnergies createDocBodySystemIntertieZonalEnergies() {
        return new DocBody.System.IntertieZonalEnergies();
    }

    /**
     * Create an instance of {@link DocBody.System.IntertieZonalEnergies.ZonalEnergies }
     * 
     */
    public DocBody.System.IntertieZonalEnergies.ZonalEnergies createDocBodySystemIntertieZonalEnergiesZonalEnergies() {
        return new DocBody.System.IntertieZonalEnergies.ZonalEnergies();
    }

    /**
     * Create an instance of {@link DocBody.System.InternalResources }
     * 
     */
    public DocBody.System.InternalResources createDocBodySystemInternalResources() {
        return new DocBody.System.InternalResources();
    }

    /**
     * Create an instance of {@link DocBody.System.InternalResources.InternalResource }
     * 
     */
    public DocBody.System.InternalResources.InternalResource createDocBodySystemInternalResourcesInternalResource() {
        return new DocBody.System.InternalResources.InternalResource();
    }

    /**
     * Create an instance of {@link DocBody.System.EmbeddedForecasts }
     * 
     */
    public DocBody.System.EmbeddedForecasts createDocBodySystemEmbeddedForecasts() {
        return new DocBody.System.EmbeddedForecasts();
    }

    /**
     * Create an instance of {@link DocBody.System.EmbeddedForecasts.EmbeddedForecast }
     * 
     */
    public DocBody.System.EmbeddedForecasts.EmbeddedForecast createDocBodySystemEmbeddedForecastsEmbeddedForecast() {
        return new DocBody.System.EmbeddedForecasts.EmbeddedForecast();
    }

    /**
     * Create an instance of {@link DocBody.System.Demands }
     * 
     */
    public DocBody.System.Demands createDocBodySystemDemands() {
        return new DocBody.System.Demands();
    }

    /**
     * Create an instance of {@link DocConfidentiality }
     * 
     */
    public DocConfidentiality createDocConfidentiality() {
        return new DocConfidentiality();
    }

    /**
     * Create an instance of {@link DocConfGroups }
     * 
     */
    public DocConfGroups createDocConfGroups() {
        return new DocConfGroups();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link DocHeader }
     * 
     */
    public DocHeader createDocHeader() {
        return new DocHeader();
    }

    /**
     * Create an instance of {@link HourlyValue }
     * 
     */
    public HourlyValue createHourlyValue() {
        return new HourlyValue();
    }

    /**
     * Create an instance of {@link DocBody.System.ORRequirements }
     * 
     */
    public DocBody.System.ORRequirements createDocBodySystemORRequirements() {
        return new DocBody.System.ORRequirements();
    }

    /**
     * Create an instance of {@link DocBody.System.TotalRequirements }
     * 
     */
    public DocBody.System.TotalRequirements createDocBodySystemTotalRequirements() {
        return new DocBody.System.TotalRequirements();
    }

    /**
     * Create an instance of {@link DocBody.System.UnscheduledResources }
     * 
     */
    public DocBody.System.UnscheduledResources createDocBodySystemUnscheduledResources() {
        return new DocBody.System.UnscheduledResources();
    }

    /**
     * Create an instance of {@link DocBody.System.UnscheduledImports }
     * 
     */
    public DocBody.System.UnscheduledImports createDocBodySystemUnscheduledImports() {
        return new DocBody.System.UnscheduledImports();
    }

    /**
     * Create an instance of {@link DocBody.System.ExcessCapacities }
     * 
     */
    public DocBody.System.ExcessCapacities createDocBodySystemExcessCapacities() {
        return new DocBody.System.ExcessCapacities();
    }

    /**
     * Create an instance of {@link DocBody.System.SupplyCushions }
     * 
     */
    public DocBody.System.SupplyCushions createDocBodySystemSupplyCushions() {
        return new DocBody.System.SupplyCushions();
    }

    /**
     * Create an instance of {@link DocBody.System.IntertieZonalEnergies.ZonalEnergies.IntertieZoneImportOffered }
     * 
     */
    public DocBody.System.IntertieZonalEnergies.ZonalEnergies.IntertieZoneImportOffered createDocBodySystemIntertieZonalEnergiesZonalEnergiesIntertieZoneImportOffered() {
        return new DocBody.System.IntertieZonalEnergies.ZonalEnergies.IntertieZoneImportOffered();
    }

    /**
     * Create an instance of {@link DocBody.System.IntertieZonalEnergies.ZonalEnergies.IntertieZoneImportScheduled }
     * 
     */
    public DocBody.System.IntertieZonalEnergies.ZonalEnergies.IntertieZoneImportScheduled createDocBodySystemIntertieZonalEnergiesZonalEnergiesIntertieZoneImportScheduled() {
        return new DocBody.System.IntertieZonalEnergies.ZonalEnergies.IntertieZoneImportScheduled();
    }

    /**
     * Create an instance of {@link DocBody.System.IntertieZonalEnergies.ZonalEnergies.IntertieZoneExportBid }
     * 
     */
    public DocBody.System.IntertieZonalEnergies.ZonalEnergies.IntertieZoneExportBid createDocBodySystemIntertieZonalEnergiesZonalEnergiesIntertieZoneExportBid() {
        return new DocBody.System.IntertieZonalEnergies.ZonalEnergies.IntertieZoneExportBid();
    }

    /**
     * Create an instance of {@link DocBody.System.IntertieZonalEnergies.ZonalEnergies.IntertieZoneExportScheduled }
     * 
     */
    public DocBody.System.IntertieZonalEnergies.ZonalEnergies.IntertieZoneExportScheduled createDocBodySystemIntertieZonalEnergiesZonalEnergiesIntertieZoneExportScheduled() {
        return new DocBody.System.IntertieZonalEnergies.ZonalEnergies.IntertieZoneExportScheduled();
    }

    /**
     * Create an instance of {@link DocBody.System.InternalResources.InternalResource.FuelOffered }
     * 
     */
    public DocBody.System.InternalResources.InternalResource.FuelOffered createDocBodySystemInternalResourcesInternalResourceFuelOffered() {
        return new DocBody.System.InternalResources.InternalResource.FuelOffered();
    }

    /**
     * Create an instance of {@link DocBody.System.InternalResources.InternalResource.FuelScheduled }
     * 
     */
    public DocBody.System.InternalResources.InternalResource.FuelScheduled createDocBodySystemInternalResourcesInternalResourceFuelScheduled() {
        return new DocBody.System.InternalResources.InternalResource.FuelScheduled();
    }

    /**
     * Create an instance of {@link DocBody.System.InternalResources.InternalResource.FuelScheduledON }
     * 
     */
    public DocBody.System.InternalResources.InternalResource.FuelScheduledON createDocBodySystemInternalResourcesInternalResourceFuelScheduledON() {
        return new DocBody.System.InternalResources.InternalResource.FuelScheduledON();
    }

    /**
     * Create an instance of {@link DocBody.System.EmbeddedForecasts.EmbeddedForecast.Forecasts }
     * 
     */
    public DocBody.System.EmbeddedForecasts.EmbeddedForecast.Forecasts createDocBodySystemEmbeddedForecastsEmbeddedForecastForecasts() {
        return new DocBody.System.EmbeddedForecasts.EmbeddedForecast.Forecasts();
    }

    /**
     * Create an instance of {@link DocBody.System.Demands.PeakDemand }
     * 
     */
    public DocBody.System.Demands.PeakDemand createDocBodySystemDemandsPeakDemand() {
        return new DocBody.System.Demands.PeakDemand();
    }

    /**
     * Create an instance of {@link DocBody.System.Demands.AverageDemand }
     * 
     */
    public DocBody.System.Demands.AverageDemand createDocBodySystemDemandsAverageDemand() {
        return new DocBody.System.Demands.AverageDemand();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfidentialityClass }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ieso.ca/schema", name = "DocConfClass")
    public JAXBElement<ConfidentialityClass> createDocConfClass(ConfidentialityClass value) {
        return new JAXBElement<ConfidentialityClass>(_DocConfClass_QNAME, ConfidentialityClass.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ieso.ca/schema", name = "CreatedAt")
    public JAXBElement<XMLGregorianCalendar> createCreatedAt(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CreatedAt_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ieso.ca/schema", name = "DocTitle")
    public JAXBElement<String> createDocTitle(String value) {
        return new JAXBElement<String>(_DocTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ieso.ca/schema", name = "DocRevision")
    public JAXBElement<BigInteger> createDocRevision(BigInteger value) {
        return new JAXBElement<BigInteger>(_DocRevision_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ieso.ca/schema", name = "DocConfGroup")
    public JAXBElement<String> createDocConfGroup(String value) {
        return new JAXBElement<String>(_DocConfGroup_QNAME, String.class, null, value);
    }

}
