//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.10 at 11:53:05 PM EST 
//


package ca.ieso.schema;

import java.math.BigDecimal;
import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the ca.ieso.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DocConfClass_QNAME = new QName("http://www.ieso.ca/schema", "DocConfClass");
    private final static QName _CreatedAt_QNAME = new QName("http://www.ieso.ca/schema", "CreatedAt");
    private final static QName _DocTitle_QNAME = new QName("http://www.ieso.ca/schema", "DocTitle");
    private final static QName _DocRevision_QNAME = new QName("http://www.ieso.ca/schema", "DocRevision");
    private final static QName _DocConfGroup_QNAME = new QName("http://www.ieso.ca/schema", "DocConfGroup");
    private final static QName _DocBodyOrganizationDataFuelDataResourceDataEnergyForecastForecastIntervalMWOutput_QNAME = new QName("http://www.ieso.ca/schema", "MWOutput");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: ca.ieso.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DocBody }
     * 
     */
    public DocBody createDocBody() {
        return new DocBody();
    }

    /**
     * Create an instance of {@link DocBody.OrganizationData }
     * 
     */
    public DocBody.OrganizationData createDocBodyOrganizationData() {
        return new DocBody.OrganizationData();
    }

    /**
     * Create an instance of {@link DocBody.OrganizationData.FuelData }
     * 
     */
    public DocBody.OrganizationData.FuelData createDocBodyOrganizationDataFuelData() {
        return new DocBody.OrganizationData.FuelData();
    }

    /**
     * Create an instance of {@link DocBody.OrganizationData.FuelData.ResourceData }
     * 
     */
    public DocBody.OrganizationData.FuelData.ResourceData createDocBodyOrganizationDataFuelDataResourceData() {
        return new DocBody.OrganizationData.FuelData.ResourceData();
    }

    /**
     * Create an instance of {@link DocBody.OrganizationData.FuelData.ResourceData.EnergyForecast }
     * 
     */
    public DocBody.OrganizationData.FuelData.ResourceData.EnergyForecast createDocBodyOrganizationDataFuelDataResourceDataEnergyForecast() {
        return new DocBody.OrganizationData.FuelData.ResourceData.EnergyForecast();
    }

    /**
     * Create an instance of {@link DocConfidentiality }
     * 
     */
    public DocConfidentiality createDocConfidentiality() {
        return new DocConfidentiality();
    }

    /**
     * Create an instance of {@link DocConfGroups }
     * 
     */
    public DocConfGroups createDocConfGroups() {
        return new DocConfGroups();
    }

    /**
     * Create an instance of {@link Document }
     * 
     */
    public Document createDocument() {
        return new Document();
    }

    /**
     * Create an instance of {@link DocHeader }
     * 
     */
    public DocHeader createDocHeader() {
        return new DocHeader();
    }

    /**
     * Create an instance of {@link DocBody.OrganizationData.FuelData.ResourceData.EnergyForecast.ForecastInterval }
     * 
     */
    public DocBody.OrganizationData.FuelData.ResourceData.EnergyForecast.ForecastInterval createDocBodyOrganizationDataFuelDataResourceDataEnergyForecastForecastInterval() {
        return new DocBody.OrganizationData.FuelData.ResourceData.EnergyForecast.ForecastInterval();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfidentialityClass }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ieso.ca/schema", name = "DocConfClass")
    public JAXBElement<ConfidentialityClass> createDocConfClass(ConfidentialityClass value) {
        return new JAXBElement<ConfidentialityClass>(_DocConfClass_QNAME, ConfidentialityClass.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ieso.ca/schema", name = "CreatedAt")
    public JAXBElement<XMLGregorianCalendar> createCreatedAt(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CreatedAt_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ieso.ca/schema", name = "DocTitle")
    public JAXBElement<String> createDocTitle(String value) {
        return new JAXBElement<String>(_DocTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ieso.ca/schema", name = "DocRevision")
    public JAXBElement<BigInteger> createDocRevision(BigInteger value) {
        return new JAXBElement<BigInteger>(_DocRevision_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ieso.ca/schema", name = "DocConfGroup")
    public JAXBElement<String> createDocConfGroup(String value) {
        return new JAXBElement<String>(_DocConfGroup_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigDecimal }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ieso.ca/schema", name = "MWOutput", scope = DocBody.OrganizationData.FuelData.ResourceData.EnergyForecast.ForecastInterval.class, defaultValue = "0")
    public JAXBElement<BigDecimal> createDocBodyOrganizationDataFuelDataResourceDataEnergyForecastForecastIntervalMWOutput(BigDecimal value) {
        return new JAXBElement<BigDecimal>(_DocBodyOrganizationDataFuelDataResourceDataEnergyForecastForecastIntervalMWOutput_QNAME, BigDecimal.class, DocBody.OrganizationData.FuelData.ResourceData.EnergyForecast.ForecastInterval.class, value);
    }

}
