//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.25 at 10:03:59 PM CST 
//


package ca.ieso.reports.schema.vgtiebreakingrankings;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="StartDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="EndDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="ResourceData" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="ResourceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="RankingMonths" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="RankingMonth" type="{http://www.w3.org/2001/XMLSchema}gYearMonth"/>
 *                             &lt;element name="RankingDays" maxOccurs="31">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="RankingDay" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                                       &lt;element name="Ranking" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "startDate",
    "endDate",
    "resourceData"
})
@XmlRootElement(name = "DocBody")
public class DocBody {

    @XmlElement(name = "StartDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar startDate;
    @XmlElement(name = "EndDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar endDate;
    @XmlElement(name = "ResourceData", required = true)
    protected List<DocBody.ResourceData> resourceData;

    /**
     * Gets the value of the startDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStartDate() {
        return startDate;
    }

    /**
     * Sets the value of the startDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStartDate(XMLGregorianCalendar value) {
        this.startDate = value;
    }

    /**
     * Gets the value of the endDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getEndDate() {
        return endDate;
    }

    /**
     * Sets the value of the endDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setEndDate(XMLGregorianCalendar value) {
        this.endDate = value;
    }

    /**
     * Gets the value of the resourceData property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resourceData property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResourceData().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocBody.ResourceData }
     * 
     * 
     */
    public List<DocBody.ResourceData> getResourceData() {
        if (resourceData == null) {
            resourceData = new ArrayList<DocBody.ResourceData>();
        }
        return this.resourceData;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="ResourceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="RankingMonths" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="RankingMonth" type="{http://www.w3.org/2001/XMLSchema}gYearMonth"/>
     *                   &lt;element name="RankingDays" maxOccurs="31">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="RankingDay" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                             &lt;element name="Ranking" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "resourceName",
        "rankingMonths"
    })
    public static class ResourceData {

        @XmlElement(name = "ResourceName", required = true)
        protected String resourceName;
        @XmlElement(name = "RankingMonths", required = true)
        protected List<DocBody.ResourceData.RankingMonths> rankingMonths;

        /**
         * Gets the value of the resourceName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResourceName() {
            return resourceName;
        }

        /**
         * Sets the value of the resourceName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResourceName(String value) {
            this.resourceName = value;
        }

        /**
         * Gets the value of the rankingMonths property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the rankingMonths property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getRankingMonths().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DocBody.ResourceData.RankingMonths }
         * 
         * 
         */
        public List<DocBody.ResourceData.RankingMonths> getRankingMonths() {
            if (rankingMonths == null) {
                rankingMonths = new ArrayList<DocBody.ResourceData.RankingMonths>();
            }
            return this.rankingMonths;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="RankingMonth" type="{http://www.w3.org/2001/XMLSchema}gYearMonth"/>
         *         &lt;element name="RankingDays" maxOccurs="31">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="RankingDay" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *                   &lt;element name="Ranking" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "rankingMonth",
            "rankingDays"
        })
        public static class RankingMonths {

            @XmlElement(name = "RankingMonth", required = true)
            @XmlSchemaType(name = "gYearMonth")
            protected XMLGregorianCalendar rankingMonth;
            @XmlElement(name = "RankingDays", required = true)
            protected List<DocBody.ResourceData.RankingMonths.RankingDays> rankingDays;

            /**
             * Gets the value of the rankingMonth property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getRankingMonth() {
                return rankingMonth;
            }

            /**
             * Sets the value of the rankingMonth property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setRankingMonth(XMLGregorianCalendar value) {
                this.rankingMonth = value;
            }

            /**
             * Gets the value of the rankingDays property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the rankingDays property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getRankingDays().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DocBody.ResourceData.RankingMonths.RankingDays }
             * 
             * 
             */
            public List<DocBody.ResourceData.RankingMonths.RankingDays> getRankingDays() {
                if (rankingDays == null) {
                    rankingDays = new ArrayList<DocBody.ResourceData.RankingMonths.RankingDays>();
                }
                return this.rankingDays;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="RankingDay" type="{http://www.w3.org/2001/XMLSchema}integer"/>
             *         &lt;element name="Ranking" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "rankingDay",
                "ranking"
            })
            public static class RankingDays {

                @XmlElement(name = "RankingDay", required = true)
                protected BigInteger rankingDay;
                @XmlElement(name = "Ranking")
                protected String ranking;

                /**
                 * Gets the value of the rankingDay property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigInteger }
                 *     
                 */
                public BigInteger getRankingDay() {
                    return rankingDay;
                }

                /**
                 * Sets the value of the rankingDay property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigInteger }
                 *     
                 */
                public void setRankingDay(BigInteger value) {
                    this.rankingDay = value;
                }

                /**
                 * Gets the value of the ranking property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getRanking() {
                    return ranking;
                }

                /**
                 * Sets the value of the ranking property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setRanking(String value) {
                    this.ranking = value;
                }

            }

        }

    }

}
