//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.25 at 10:03:54 PM CST 
//


package ca.ieso.reports.schema.trapreauctioninterfacehistorymonthly;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ForMonth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="IntertieFlowsAndCapabilitiesByDate" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="DeliveryDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *                   &lt;element name="IntertieFlowsAndCapabilities" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="IntertieZoneName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="HourlyFlowsAndCapabilities" maxOccurs="24">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="DeliveryHour" type="{http://www.ieso.ca/schema}Hour1To24"/>
 *                                       &lt;element name="ScheduledFlow" type="{http://www.ieso.ca/schema}MW_decimal5.1"/>
 *                                       &lt;element name="ActualFlow" type="{http://www.ieso.ca/schema}MW_decimal5.1"/>
 *                                       &lt;element name="IntertieTransferCapabilityIn" type="{http://www.ieso.ca/schema}MW_decimal5.1"/>
 *                                       &lt;element name="IntertieTransferCapabilityOut" type="{http://www.ieso.ca/schema}MW_decimal5.1"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "forMonth",
    "intertieFlowsAndCapabilitiesByDate"
})
@XmlRootElement(name = "DocBody")
public class DocBody {

    @XmlElement(name = "ForMonth", required = true)
    protected String forMonth;
    @XmlElement(name = "IntertieFlowsAndCapabilitiesByDate", required = true)
    protected List<DocBody.IntertieFlowsAndCapabilitiesByDate> intertieFlowsAndCapabilitiesByDate;

    /**
     * Gets the value of the forMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForMonth() {
        return forMonth;
    }

    /**
     * Sets the value of the forMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForMonth(String value) {
        this.forMonth = value;
    }

    /**
     * Gets the value of the intertieFlowsAndCapabilitiesByDate property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the intertieFlowsAndCapabilitiesByDate property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIntertieFlowsAndCapabilitiesByDate().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocBody.IntertieFlowsAndCapabilitiesByDate }
     * 
     * 
     */
    public List<DocBody.IntertieFlowsAndCapabilitiesByDate> getIntertieFlowsAndCapabilitiesByDate() {
        if (intertieFlowsAndCapabilitiesByDate == null) {
            intertieFlowsAndCapabilitiesByDate = new ArrayList<DocBody.IntertieFlowsAndCapabilitiesByDate>();
        }
        return this.intertieFlowsAndCapabilitiesByDate;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="DeliveryDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
     *         &lt;element name="IntertieFlowsAndCapabilities" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="IntertieZoneName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="HourlyFlowsAndCapabilities" maxOccurs="24">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="DeliveryHour" type="{http://www.ieso.ca/schema}Hour1To24"/>
     *                             &lt;element name="ScheduledFlow" type="{http://www.ieso.ca/schema}MW_decimal5.1"/>
     *                             &lt;element name="ActualFlow" type="{http://www.ieso.ca/schema}MW_decimal5.1"/>
     *                             &lt;element name="IntertieTransferCapabilityIn" type="{http://www.ieso.ca/schema}MW_decimal5.1"/>
     *                             &lt;element name="IntertieTransferCapabilityOut" type="{http://www.ieso.ca/schema}MW_decimal5.1"/>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "deliveryDate",
        "intertieFlowsAndCapabilities"
    })
    public static class IntertieFlowsAndCapabilitiesByDate {

        @XmlElement(name = "DeliveryDate", required = true)
        @XmlSchemaType(name = "date")
        protected XMLGregorianCalendar deliveryDate;
        @XmlElement(name = "IntertieFlowsAndCapabilities", required = true)
        protected List<DocBody.IntertieFlowsAndCapabilitiesByDate.IntertieFlowsAndCapabilities> intertieFlowsAndCapabilities;

        /**
         * Gets the value of the deliveryDate property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public XMLGregorianCalendar getDeliveryDate() {
            return deliveryDate;
        }

        /**
         * Sets the value of the deliveryDate property.
         * 
         * @param value
         *     allowed object is
         *     {@link XMLGregorianCalendar }
         *     
         */
        public void setDeliveryDate(XMLGregorianCalendar value) {
            this.deliveryDate = value;
        }

        /**
         * Gets the value of the intertieFlowsAndCapabilities property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the intertieFlowsAndCapabilities property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIntertieFlowsAndCapabilities().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DocBody.IntertieFlowsAndCapabilitiesByDate.IntertieFlowsAndCapabilities }
         * 
         * 
         */
        public List<DocBody.IntertieFlowsAndCapabilitiesByDate.IntertieFlowsAndCapabilities> getIntertieFlowsAndCapabilities() {
            if (intertieFlowsAndCapabilities == null) {
                intertieFlowsAndCapabilities = new ArrayList<DocBody.IntertieFlowsAndCapabilitiesByDate.IntertieFlowsAndCapabilities>();
            }
            return this.intertieFlowsAndCapabilities;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="IntertieZoneName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="HourlyFlowsAndCapabilities" maxOccurs="24">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="DeliveryHour" type="{http://www.ieso.ca/schema}Hour1To24"/>
         *                   &lt;element name="ScheduledFlow" type="{http://www.ieso.ca/schema}MW_decimal5.1"/>
         *                   &lt;element name="ActualFlow" type="{http://www.ieso.ca/schema}MW_decimal5.1"/>
         *                   &lt;element name="IntertieTransferCapabilityIn" type="{http://www.ieso.ca/schema}MW_decimal5.1"/>
         *                   &lt;element name="IntertieTransferCapabilityOut" type="{http://www.ieso.ca/schema}MW_decimal5.1"/>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "intertieZoneName",
            "hourlyFlowsAndCapabilities"
        })
        public static class IntertieFlowsAndCapabilities {

            @XmlElement(name = "IntertieZoneName", required = true)
            protected String intertieZoneName;
            @XmlElement(name = "HourlyFlowsAndCapabilities", required = true)
            protected List<DocBody.IntertieFlowsAndCapabilitiesByDate.IntertieFlowsAndCapabilities.HourlyFlowsAndCapabilities> hourlyFlowsAndCapabilities;

            /**
             * Gets the value of the intertieZoneName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getIntertieZoneName() {
                return intertieZoneName;
            }

            /**
             * Sets the value of the intertieZoneName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setIntertieZoneName(String value) {
                this.intertieZoneName = value;
            }

            /**
             * Gets the value of the hourlyFlowsAndCapabilities property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the hourlyFlowsAndCapabilities property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getHourlyFlowsAndCapabilities().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DocBody.IntertieFlowsAndCapabilitiesByDate.IntertieFlowsAndCapabilities.HourlyFlowsAndCapabilities }
             * 
             * 
             */
            public List<DocBody.IntertieFlowsAndCapabilitiesByDate.IntertieFlowsAndCapabilities.HourlyFlowsAndCapabilities> getHourlyFlowsAndCapabilities() {
                if (hourlyFlowsAndCapabilities == null) {
                    hourlyFlowsAndCapabilities = new ArrayList<DocBody.IntertieFlowsAndCapabilitiesByDate.IntertieFlowsAndCapabilities.HourlyFlowsAndCapabilities>();
                }
                return this.hourlyFlowsAndCapabilities;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="DeliveryHour" type="{http://www.ieso.ca/schema}Hour1To24"/>
             *         &lt;element name="ScheduledFlow" type="{http://www.ieso.ca/schema}MW_decimal5.1"/>
             *         &lt;element name="ActualFlow" type="{http://www.ieso.ca/schema}MW_decimal5.1"/>
             *         &lt;element name="IntertieTransferCapabilityIn" type="{http://www.ieso.ca/schema}MW_decimal5.1"/>
             *         &lt;element name="IntertieTransferCapabilityOut" type="{http://www.ieso.ca/schema}MW_decimal5.1"/>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "deliveryHour",
                "scheduledFlow",
                "actualFlow",
                "intertieTransferCapabilityIn",
                "intertieTransferCapabilityOut"
            })
            public static class HourlyFlowsAndCapabilities {

                @XmlElement(name = "DeliveryHour")
                protected int deliveryHour;
                @XmlElement(name = "ScheduledFlow", required = true)
                protected BigDecimal scheduledFlow;
                @XmlElement(name = "ActualFlow", required = true)
                protected BigDecimal actualFlow;
                @XmlElement(name = "IntertieTransferCapabilityIn", required = true)
                protected BigDecimal intertieTransferCapabilityIn;
                @XmlElement(name = "IntertieTransferCapabilityOut", required = true)
                protected BigDecimal intertieTransferCapabilityOut;

                /**
                 * Gets the value of the deliveryHour property.
                 * 
                 */
                public int getDeliveryHour() {
                    return deliveryHour;
                }

                /**
                 * Sets the value of the deliveryHour property.
                 * 
                 */
                public void setDeliveryHour(int value) {
                    this.deliveryHour = value;
                }

                /**
                 * Gets the value of the scheduledFlow property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getScheduledFlow() {
                    return scheduledFlow;
                }

                /**
                 * Sets the value of the scheduledFlow property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setScheduledFlow(BigDecimal value) {
                    this.scheduledFlow = value;
                }

                /**
                 * Gets the value of the actualFlow property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getActualFlow() {
                    return actualFlow;
                }

                /**
                 * Sets the value of the actualFlow property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setActualFlow(BigDecimal value) {
                    this.actualFlow = value;
                }

                /**
                 * Gets the value of the intertieTransferCapabilityIn property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getIntertieTransferCapabilityIn() {
                    return intertieTransferCapabilityIn;
                }

                /**
                 * Sets the value of the intertieTransferCapabilityIn property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setIntertieTransferCapabilityIn(BigDecimal value) {
                    this.intertieTransferCapabilityIn = value;
                }

                /**
                 * Gets the value of the intertieTransferCapabilityOut property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link BigDecimal }
                 *     
                 */
                public BigDecimal getIntertieTransferCapabilityOut() {
                    return intertieTransferCapabilityOut;
                }

                /**
                 * Sets the value of the intertieTransferCapabilityOut property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link BigDecimal }
                 *     
                 */
                public void setIntertieTransferCapabilityOut(BigDecimal value) {
                    this.intertieTransferCapabilityOut = value;
                }

            }

        }

    }

}
