//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.24 at 10:52:53 AM CST 
//


package ca.ieso.reports.schema.predispareareserveconst;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DeliveryDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="RegionalAreaEnergies" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RegionalArea" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="HourlyEnergies" maxOccurs="4">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PriceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="HourlyEnergy" type="{http://www.ieso.ca/schema}HourlyValue" maxOccurs="24"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deliveryDate",
    "regionalAreaEnergies"
})
@XmlRootElement(name = "DocBody")
public class DocBody {

    @XmlElement(name = "DeliveryDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar deliveryDate;
    @XmlElement(name = "RegionalAreaEnergies", required = true)
    protected List<DocBody.RegionalAreaEnergies> regionalAreaEnergies;

    /**
     * Gets the value of the deliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * Sets the value of the deliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeliveryDate(XMLGregorianCalendar value) {
        this.deliveryDate = value;
    }

    /**
     * Gets the value of the regionalAreaEnergies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the regionalAreaEnergies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegionalAreaEnergies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocBody.RegionalAreaEnergies }
     * 
     * 
     */
    public List<DocBody.RegionalAreaEnergies> getRegionalAreaEnergies() {
        if (regionalAreaEnergies == null) {
            regionalAreaEnergies = new ArrayList<DocBody.RegionalAreaEnergies>();
        }
        return this.regionalAreaEnergies;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RegionalArea" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="HourlyEnergies" maxOccurs="4">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PriceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="HourlyEnergy" type="{http://www.ieso.ca/schema}HourlyValue" maxOccurs="24"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "regionalArea",
        "hourlyEnergies"
    })
    public static class RegionalAreaEnergies {

        @XmlElement(name = "RegionalArea", required = true)
        protected String regionalArea;
        @XmlElement(name = "HourlyEnergies", required = true)
        protected List<DocBody.RegionalAreaEnergies.HourlyEnergies> hourlyEnergies;

        /**
         * Gets the value of the regionalArea property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegionalArea() {
            return regionalArea;
        }

        /**
         * Sets the value of the regionalArea property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegionalArea(String value) {
            this.regionalArea = value;
        }

        /**
         * Gets the value of the hourlyEnergies property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the hourlyEnergies property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getHourlyEnergies().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DocBody.RegionalAreaEnergies.HourlyEnergies }
         * 
         * 
         */
        public List<DocBody.RegionalAreaEnergies.HourlyEnergies> getHourlyEnergies() {
            if (hourlyEnergies == null) {
                hourlyEnergies = new ArrayList<DocBody.RegionalAreaEnergies.HourlyEnergies>();
            }
            return this.hourlyEnergies;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="PriceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="HourlyEnergy" type="{http://www.ieso.ca/schema}HourlyValue" maxOccurs="24"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "priceType",
            "hourlyEnergy"
        })
        public static class HourlyEnergies {

            @XmlElement(name = "PriceType", required = true)
            protected String priceType;
            @XmlElement(name = "HourlyEnergy", required = true)
            protected List<HourlyValue> hourlyEnergy;

            /**
             * Gets the value of the priceType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPriceType() {
                return priceType;
            }

            /**
             * Sets the value of the priceType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPriceType(String value) {
                this.priceType = value;
            }

            /**
             * Gets the value of the hourlyEnergy property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the hourlyEnergy property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getHourlyEnergy().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link HourlyValue }
             * 
             * 
             */
            public List<HourlyValue> getHourlyEnergy() {
                if (hourlyEnergy == null) {
                    hourlyEnergy = new ArrayList<HourlyValue>();
                }
                return this.hourlyEnergy;
            }

        }

    }

}
