//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.25 at 12:17:45 PM CST 
//


package ca.ieso.reports.schema.realtimeareareserveconst;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DeliveryDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="DeliveryHour" type="{http://www.ieso.ca/schema}Hour1To24"/>
 *         &lt;element name="RegionalAreaEnergies" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="RegionalArea" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="IntervalEnergies" maxOccurs="4">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PriceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="IntervalEnergy" maxOccurs="12">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;extension base="{http://www.ieso.ca/schema}IntervalEnergyValues">
 *                                     &lt;sequence>
 *                                       &lt;element name="Flag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                     &lt;/sequence>
 *                                   &lt;/extension>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deliveryDate",
    "deliveryHour",
    "regionalAreaEnergies"
})
@XmlRootElement(name = "DocBody")
public class DocBody {

    @XmlElement(name = "DeliveryDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar deliveryDate;
    @XmlElement(name = "DeliveryHour")
    protected int deliveryHour;
    @XmlElement(name = "RegionalAreaEnergies", required = true)
    protected List<DocBody.RegionalAreaEnergies> regionalAreaEnergies;

    /**
     * Gets the value of the deliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * Sets the value of the deliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeliveryDate(XMLGregorianCalendar value) {
        this.deliveryDate = value;
    }

    /**
     * Gets the value of the deliveryHour property.
     * 
     */
    public int getDeliveryHour() {
        return deliveryHour;
    }

    /**
     * Sets the value of the deliveryHour property.
     * 
     */
    public void setDeliveryHour(int value) {
        this.deliveryHour = value;
    }

    /**
     * Gets the value of the regionalAreaEnergies property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the regionalAreaEnergies property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRegionalAreaEnergies().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocBody.RegionalAreaEnergies }
     * 
     * 
     */
    public List<DocBody.RegionalAreaEnergies> getRegionalAreaEnergies() {
        if (regionalAreaEnergies == null) {
            regionalAreaEnergies = new ArrayList<DocBody.RegionalAreaEnergies>();
        }
        return this.regionalAreaEnergies;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="RegionalArea" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="IntervalEnergies" maxOccurs="4">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PriceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="IntervalEnergy" maxOccurs="12">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;extension base="{http://www.ieso.ca/schema}IntervalEnergyValues">
     *                           &lt;sequence>
     *                             &lt;element name="Flag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                           &lt;/sequence>
     *                         &lt;/extension>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "regionalArea",
        "intervalEnergies"
    })
    public static class RegionalAreaEnergies {

        @XmlElement(name = "RegionalArea", required = true)
        protected String regionalArea;
        @XmlElement(name = "IntervalEnergies", required = true)
        protected List<DocBody.RegionalAreaEnergies.IntervalEnergies> intervalEnergies;

        /**
         * Gets the value of the regionalArea property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getRegionalArea() {
            return regionalArea;
        }

        /**
         * Sets the value of the regionalArea property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setRegionalArea(String value) {
            this.regionalArea = value;
        }

        /**
         * Gets the value of the intervalEnergies property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the intervalEnergies property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getIntervalEnergies().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DocBody.RegionalAreaEnergies.IntervalEnergies }
         * 
         * 
         */
        public List<DocBody.RegionalAreaEnergies.IntervalEnergies> getIntervalEnergies() {
            if (intervalEnergies == null) {
                intervalEnergies = new ArrayList<DocBody.RegionalAreaEnergies.IntervalEnergies>();
            }
            return this.intervalEnergies;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="PriceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="IntervalEnergy" maxOccurs="12">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;extension base="{http://www.ieso.ca/schema}IntervalEnergyValues">
         *                 &lt;sequence>
         *                   &lt;element name="Flag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                 &lt;/sequence>
         *               &lt;/extension>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "priceType",
            "intervalEnergy"
        })
        public static class IntervalEnergies {

            @XmlElement(name = "PriceType", required = true)
            protected String priceType;
            @XmlElement(name = "IntervalEnergy", required = true)
            protected List<DocBody.RegionalAreaEnergies.IntervalEnergies.IntervalEnergy> intervalEnergy;

            /**
             * Gets the value of the priceType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPriceType() {
                return priceType;
            }

            /**
             * Sets the value of the priceType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPriceType(String value) {
                this.priceType = value;
            }

            /**
             * Gets the value of the intervalEnergy property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the intervalEnergy property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getIntervalEnergy().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DocBody.RegionalAreaEnergies.IntervalEnergies.IntervalEnergy }
             * 
             * 
             */
            public List<DocBody.RegionalAreaEnergies.IntervalEnergies.IntervalEnergy> getIntervalEnergy() {
                if (intervalEnergy == null) {
                    intervalEnergy = new ArrayList<DocBody.RegionalAreaEnergies.IntervalEnergies.IntervalEnergy>();
                }
                return this.intervalEnergy;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;extension base="{http://www.ieso.ca/schema}IntervalEnergyValues">
             *       &lt;sequence>
             *         &lt;element name="Flag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *       &lt;/sequence>
             *     &lt;/extension>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "flag"
            })
            public static class IntervalEnergy
                extends IntervalEnergyValues
            {

                @XmlElement(name = "Flag")
                protected String flag;

                /**
                 * Gets the value of the flag property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getFlag() {
                    return flag;
                }

                /**
                 * Sets the value of the flag property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setFlag(String value) {
                    this.flag = value;
                }

            }

        }

    }

}
