//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.24 at 10:52:41 AM CST 
//


package ca.ieso.reports.schema.intertiescheduleflow;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence maxOccurs="unbounded">
 *         &lt;element ref="{http://www.theIMO.com/schema}IMODocHeader"/>
 *         &lt;element ref="{http://www.theIMO.com/schema}IMODocBody"/>
 *       &lt;/sequence>
 *       &lt;attribute name="docID" type="{http://www.theIMO.com/schema}docID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "imoDocHeaderAndIMODocBody"
})
@XmlRootElement(name = "IMODocument")
public class IMODocument {

    @XmlElements({
        @XmlElement(name = "IMODocHeader", required = true, type = IMODocHeader.class),
        @XmlElement(name = "IMODocBody", required = true, type = IMODocBody.class)
    })
    protected List<Object> imoDocHeaderAndIMODocBody;
    @XmlAttribute(name = "docID")
    protected String docID;

    /**
     * Gets the value of the imoDocHeaderAndIMODocBody property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the imoDocHeaderAndIMODocBody property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIMODocHeaderAndIMODocBody().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link IMODocHeader }
     * {@link IMODocBody }
     * 
     * 
     */
    public List<Object> getIMODocHeaderAndIMODocBody() {
        if (imoDocHeaderAndIMODocBody == null) {
            imoDocHeaderAndIMODocBody = new ArrayList<Object>();
        }
        return this.imoDocHeaderAndIMODocBody;
    }

    /**
     * Gets the value of the docID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDocID() {
        return docID;
    }

    /**
     * Sets the value of the docID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDocID(String value) {
        this.docID = value;
    }

}
