//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.23 at 08:28:59 AM CST 
//


package ca.ieso.reports.schema.iomspublichistoricoutagehour;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="OutageRangeStart" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="OutageRangeEnd" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *         &lt;element name="OutageRequest" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="OutageID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="AdvanceOutageApprovalCode" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="FinalOutageApprovalCode" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="OutageCompletionCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                   &lt;element name="OutageCompletionStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="EquipmentConditionPlan" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="EquipmentConditionPlanID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="EquipmentGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="EquipmentLocation1" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="EquipmentLocation2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                             &lt;element name="EquipmentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="EquipmentVoltageLevelCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="EquipmentVoltageLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="EquipmentTypeCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="EquipmentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="OutageEventCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="OutageEvent" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="EquipmentStatusCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="EquipmentStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="EquipmentProtectionCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="EquipmentProtection" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ActualOutageStart" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                             &lt;element name="ActualOutageEnd" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
 *                             &lt;element name="EquipmentRecallUnitsCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *                             &lt;element name="EquipmentRecallUnits" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="EquipmentRecallTime" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "outageRangeStart",
    "outageRangeEnd",
    "outageRequest"
})
@XmlRootElement(name = "DocBody")
public class DocBody {

    @XmlElement(name = "OutageRangeStart", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar outageRangeStart;
    @XmlElement(name = "OutageRangeEnd", required = true)
    @XmlSchemaType(name = "dateTime")
    protected XMLGregorianCalendar outageRangeEnd;
    @XmlElement(name = "OutageRequest", required = true)
    protected List<DocBody.OutageRequest> outageRequest;

    /**
     * Gets the value of the outageRangeStart property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOutageRangeStart() {
        return outageRangeStart;
    }

    /**
     * Sets the value of the outageRangeStart property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOutageRangeStart(XMLGregorianCalendar value) {
        this.outageRangeStart = value;
    }

    /**
     * Gets the value of the outageRangeEnd property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getOutageRangeEnd() {
        return outageRangeEnd;
    }

    /**
     * Sets the value of the outageRangeEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setOutageRangeEnd(XMLGregorianCalendar value) {
        this.outageRangeEnd = value;
    }

    /**
     * Gets the value of the outageRequest property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outageRequest property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutageRequest().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocBody.OutageRequest }
     * 
     * 
     */
    public List<DocBody.OutageRequest> getOutageRequest() {
        if (outageRequest == null) {
            outageRequest = new ArrayList<DocBody.OutageRequest>();
        }
        return this.outageRequest;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="OutageID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="AdvanceOutageApprovalCode" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="FinalOutageApprovalCode" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="OutageCompletionCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *         &lt;element name="OutageCompletionStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="EquipmentConditionPlan" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="EquipmentConditionPlanID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="EquipmentGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="EquipmentLocation1" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="EquipmentLocation2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                   &lt;element name="EquipmentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="EquipmentVoltageLevelCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="EquipmentVoltageLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="EquipmentTypeCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="EquipmentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="OutageEventCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="OutageEvent" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="EquipmentStatusCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="EquipmentStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="EquipmentProtectionCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="EquipmentProtection" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ActualOutageStart" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *                   &lt;element name="ActualOutageEnd" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
     *                   &lt;element name="EquipmentRecallUnitsCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
     *                   &lt;element name="EquipmentRecallUnits" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="EquipmentRecallTime" type="{http://www.w3.org/2001/XMLSchema}double"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "outageID",
        "advanceOutageApprovalCode",
        "finalOutageApprovalCode",
        "outageCompletionCode",
        "outageCompletionStatus",
        "equipmentConditionPlan"
    })
    public static class OutageRequest {

        @XmlElement(name = "OutageID", required = true)
        protected BigInteger outageID;
        @XmlElement(name = "AdvanceOutageApprovalCode")
        protected BigInteger advanceOutageApprovalCode;
        @XmlElement(name = "FinalOutageApprovalCode")
        protected BigInteger finalOutageApprovalCode;
        @XmlElement(name = "OutageCompletionCode", required = true)
        protected BigInteger outageCompletionCode;
        @XmlElement(name = "OutageCompletionStatus", required = true)
        protected String outageCompletionStatus;
        @XmlElement(name = "EquipmentConditionPlan", required = true)
        protected List<DocBody.OutageRequest.EquipmentConditionPlan> equipmentConditionPlan;

        /**
         * Gets the value of the outageID property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getOutageID() {
            return outageID;
        }

        /**
         * Sets the value of the outageID property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setOutageID(BigInteger value) {
            this.outageID = value;
        }

        /**
         * Gets the value of the advanceOutageApprovalCode property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getAdvanceOutageApprovalCode() {
            return advanceOutageApprovalCode;
        }

        /**
         * Sets the value of the advanceOutageApprovalCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setAdvanceOutageApprovalCode(BigInteger value) {
            this.advanceOutageApprovalCode = value;
        }

        /**
         * Gets the value of the finalOutageApprovalCode property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getFinalOutageApprovalCode() {
            return finalOutageApprovalCode;
        }

        /**
         * Sets the value of the finalOutageApprovalCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setFinalOutageApprovalCode(BigInteger value) {
            this.finalOutageApprovalCode = value;
        }

        /**
         * Gets the value of the outageCompletionCode property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getOutageCompletionCode() {
            return outageCompletionCode;
        }

        /**
         * Sets the value of the outageCompletionCode property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setOutageCompletionCode(BigInteger value) {
            this.outageCompletionCode = value;
        }

        /**
         * Gets the value of the outageCompletionStatus property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOutageCompletionStatus() {
            return outageCompletionStatus;
        }

        /**
         * Sets the value of the outageCompletionStatus property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOutageCompletionStatus(String value) {
            this.outageCompletionStatus = value;
        }

        /**
         * Gets the value of the equipmentConditionPlan property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the equipmentConditionPlan property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getEquipmentConditionPlan().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DocBody.OutageRequest.EquipmentConditionPlan }
         * 
         * 
         */
        public List<DocBody.OutageRequest.EquipmentConditionPlan> getEquipmentConditionPlan() {
            if (equipmentConditionPlan == null) {
                equipmentConditionPlan = new ArrayList<DocBody.OutageRequest.EquipmentConditionPlan>();
            }
            return this.equipmentConditionPlan;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="EquipmentConditionPlanID" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="EquipmentGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="EquipmentLocation1" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="EquipmentLocation2" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *         &lt;element name="EquipmentName" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="EquipmentVoltageLevelCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="EquipmentVoltageLevel" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="EquipmentTypeCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="EquipmentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="OutageEventCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="OutageEvent" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="EquipmentStatusCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="EquipmentStatus" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="EquipmentProtectionCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="EquipmentProtection" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ActualOutageStart" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
         *         &lt;element name="ActualOutageEnd" type="{http://www.w3.org/2001/XMLSchema}dateTime" minOccurs="0"/>
         *         &lt;element name="EquipmentRecallUnitsCode" type="{http://www.w3.org/2001/XMLSchema}integer"/>
         *         &lt;element name="EquipmentRecallUnits" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="EquipmentRecallTime" type="{http://www.w3.org/2001/XMLSchema}double"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "equipmentConditionPlanID",
            "equipmentGroup",
            "equipmentLocation1",
            "equipmentLocation2",
            "equipmentName",
            "equipmentVoltageLevelCode",
            "equipmentVoltageLevel",
            "equipmentTypeCode",
            "equipmentType",
            "outageEventCode",
            "outageEvent",
            "equipmentStatusCode",
            "equipmentStatus",
            "equipmentProtectionCode",
            "equipmentProtection",
            "actualOutageStart",
            "actualOutageEnd",
            "equipmentRecallUnitsCode",
            "equipmentRecallUnits",
            "equipmentRecallTime"
        })
        public static class EquipmentConditionPlan {

            @XmlElement(name = "EquipmentConditionPlanID", required = true)
            protected BigInteger equipmentConditionPlanID;
            @XmlElement(name = "EquipmentGroup")
            protected String equipmentGroup;
            @XmlElement(name = "EquipmentLocation1", required = true)
            protected String equipmentLocation1;
            @XmlElement(name = "EquipmentLocation2")
            protected String equipmentLocation2;
            @XmlElement(name = "EquipmentName", required = true)
            protected String equipmentName;
            @XmlElement(name = "EquipmentVoltageLevelCode", required = true)
            protected BigInteger equipmentVoltageLevelCode;
            @XmlElement(name = "EquipmentVoltageLevel", required = true)
            protected String equipmentVoltageLevel;
            @XmlElement(name = "EquipmentTypeCode", required = true)
            protected BigInteger equipmentTypeCode;
            @XmlElement(name = "EquipmentType", required = true)
            protected String equipmentType;
            @XmlElement(name = "OutageEventCode", required = true)
            protected BigInteger outageEventCode;
            @XmlElement(name = "OutageEvent", required = true)
            protected String outageEvent;
            @XmlElement(name = "EquipmentStatusCode", required = true)
            protected BigInteger equipmentStatusCode;
            @XmlElement(name = "EquipmentStatus", required = true)
            protected String equipmentStatus;
            @XmlElement(name = "EquipmentProtectionCode", required = true)
            protected BigInteger equipmentProtectionCode;
            @XmlElement(name = "EquipmentProtection", required = true)
            protected String equipmentProtection;
            @XmlElement(name = "ActualOutageStart", required = true)
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar actualOutageStart;
            @XmlElement(name = "ActualOutageEnd")
            @XmlSchemaType(name = "dateTime")
            protected XMLGregorianCalendar actualOutageEnd;
            @XmlElement(name = "EquipmentRecallUnitsCode", required = true)
            protected BigInteger equipmentRecallUnitsCode;
            @XmlElement(name = "EquipmentRecallUnits", required = true)
            protected String equipmentRecallUnits;
            @XmlElement(name = "EquipmentRecallTime")
            protected double equipmentRecallTime;

            /**
             * Gets the value of the equipmentConditionPlanID property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getEquipmentConditionPlanID() {
                return equipmentConditionPlanID;
            }

            /**
             * Sets the value of the equipmentConditionPlanID property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setEquipmentConditionPlanID(BigInteger value) {
                this.equipmentConditionPlanID = value;
            }

            /**
             * Gets the value of the equipmentGroup property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEquipmentGroup() {
                return equipmentGroup;
            }

            /**
             * Sets the value of the equipmentGroup property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEquipmentGroup(String value) {
                this.equipmentGroup = value;
            }

            /**
             * Gets the value of the equipmentLocation1 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEquipmentLocation1() {
                return equipmentLocation1;
            }

            /**
             * Sets the value of the equipmentLocation1 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEquipmentLocation1(String value) {
                this.equipmentLocation1 = value;
            }

            /**
             * Gets the value of the equipmentLocation2 property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEquipmentLocation2() {
                return equipmentLocation2;
            }

            /**
             * Sets the value of the equipmentLocation2 property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEquipmentLocation2(String value) {
                this.equipmentLocation2 = value;
            }

            /**
             * Gets the value of the equipmentName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEquipmentName() {
                return equipmentName;
            }

            /**
             * Sets the value of the equipmentName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEquipmentName(String value) {
                this.equipmentName = value;
            }

            /**
             * Gets the value of the equipmentVoltageLevelCode property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getEquipmentVoltageLevelCode() {
                return equipmentVoltageLevelCode;
            }

            /**
             * Sets the value of the equipmentVoltageLevelCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setEquipmentVoltageLevelCode(BigInteger value) {
                this.equipmentVoltageLevelCode = value;
            }

            /**
             * Gets the value of the equipmentVoltageLevel property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEquipmentVoltageLevel() {
                return equipmentVoltageLevel;
            }

            /**
             * Sets the value of the equipmentVoltageLevel property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEquipmentVoltageLevel(String value) {
                this.equipmentVoltageLevel = value;
            }

            /**
             * Gets the value of the equipmentTypeCode property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getEquipmentTypeCode() {
                return equipmentTypeCode;
            }

            /**
             * Sets the value of the equipmentTypeCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setEquipmentTypeCode(BigInteger value) {
                this.equipmentTypeCode = value;
            }

            /**
             * Gets the value of the equipmentType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEquipmentType() {
                return equipmentType;
            }

            /**
             * Sets the value of the equipmentType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEquipmentType(String value) {
                this.equipmentType = value;
            }

            /**
             * Gets the value of the outageEventCode property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getOutageEventCode() {
                return outageEventCode;
            }

            /**
             * Sets the value of the outageEventCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setOutageEventCode(BigInteger value) {
                this.outageEventCode = value;
            }

            /**
             * Gets the value of the outageEvent property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getOutageEvent() {
                return outageEvent;
            }

            /**
             * Sets the value of the outageEvent property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setOutageEvent(String value) {
                this.outageEvent = value;
            }

            /**
             * Gets the value of the equipmentStatusCode property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getEquipmentStatusCode() {
                return equipmentStatusCode;
            }

            /**
             * Sets the value of the equipmentStatusCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setEquipmentStatusCode(BigInteger value) {
                this.equipmentStatusCode = value;
            }

            /**
             * Gets the value of the equipmentStatus property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEquipmentStatus() {
                return equipmentStatus;
            }

            /**
             * Sets the value of the equipmentStatus property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEquipmentStatus(String value) {
                this.equipmentStatus = value;
            }

            /**
             * Gets the value of the equipmentProtectionCode property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getEquipmentProtectionCode() {
                return equipmentProtectionCode;
            }

            /**
             * Sets the value of the equipmentProtectionCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setEquipmentProtectionCode(BigInteger value) {
                this.equipmentProtectionCode = value;
            }

            /**
             * Gets the value of the equipmentProtection property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEquipmentProtection() {
                return equipmentProtection;
            }

            /**
             * Sets the value of the equipmentProtection property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEquipmentProtection(String value) {
                this.equipmentProtection = value;
            }

            /**
             * Gets the value of the actualOutageStart property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getActualOutageStart() {
                return actualOutageStart;
            }

            /**
             * Sets the value of the actualOutageStart property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setActualOutageStart(XMLGregorianCalendar value) {
                this.actualOutageStart = value;
            }

            /**
             * Gets the value of the actualOutageEnd property.
             * 
             * @return
             *     possible object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public XMLGregorianCalendar getActualOutageEnd() {
                return actualOutageEnd;
            }

            /**
             * Sets the value of the actualOutageEnd property.
             * 
             * @param value
             *     allowed object is
             *     {@link XMLGregorianCalendar }
             *     
             */
            public void setActualOutageEnd(XMLGregorianCalendar value) {
                this.actualOutageEnd = value;
            }

            /**
             * Gets the value of the equipmentRecallUnitsCode property.
             * 
             * @return
             *     possible object is
             *     {@link BigInteger }
             *     
             */
            public BigInteger getEquipmentRecallUnitsCode() {
                return equipmentRecallUnitsCode;
            }

            /**
             * Sets the value of the equipmentRecallUnitsCode property.
             * 
             * @param value
             *     allowed object is
             *     {@link BigInteger }
             *     
             */
            public void setEquipmentRecallUnitsCode(BigInteger value) {
                this.equipmentRecallUnitsCode = value;
            }

            /**
             * Gets the value of the equipmentRecallUnits property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getEquipmentRecallUnits() {
                return equipmentRecallUnits;
            }

            /**
             * Sets the value of the equipmentRecallUnits property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setEquipmentRecallUnits(String value) {
                this.equipmentRecallUnits = value;
            }

            /**
             * Gets the value of the equipmentRecallTime property.
             * 
             */
            public double getEquipmentRecallTime() {
                return equipmentRecallTime;
            }

            /**
             * Sets the value of the equipmentRecallTime property.
             * 
             */
            public void setEquipmentRecallTime(double value) {
                this.equipmentRecallTime = value;
            }

        }

    }

}
