//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.21 at 09:18:50 AM CST 
//


package ca.ieso.reports.schema.genoutputcapability;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="Generators">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence maxOccurs="unbounded">
 *                   &lt;element name="Generator">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="GeneratorName">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="255"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="FuelType">
 *                               &lt;simpleType>
 *                                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                                   &lt;minLength value="1"/>
 *                                   &lt;maxLength value="15"/>
 *                                 &lt;/restriction>
 *                               &lt;/simpleType>
 *                             &lt;/element>
 *                             &lt;element name="Outputs">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence maxOccurs="24">
 *                                       &lt;element name="Output">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Hour" type="{http://www.theIMO.com/schema}Hour1To24"/>
 *                                                 &lt;element name="EnergyMW" type="{http://www.theIMO.com/schema}MW_float" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                             &lt;element name="Capabilities">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence maxOccurs="24">
 *                                       &lt;element name="Capability">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Hour" type="{http://www.theIMO.com/schema}Hour1To24"/>
 *                                                 &lt;element name="EnergyMW" type="{http://www.theIMO.com/schema}MW_float"/>
 *                                               &lt;/sequence>
 *                                             &lt;/restriction>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "date",
    "generators"
})
@XmlRootElement(name = "IMODocBody")
public class IMODocBody {

    @XmlElement(name = "Date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar date;
    @XmlElement(name = "Generators", required = true)
    protected IMODocBody.Generators generators;

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDate(XMLGregorianCalendar value) {
        this.date = value;
    }

    /**
     * Gets the value of the generators property.
     * 
     * @return
     *     possible object is
     *     {@link IMODocBody.Generators }
     *     
     */
    public IMODocBody.Generators getGenerators() {
        return generators;
    }

    /**
     * Sets the value of the generators property.
     * 
     * @param value
     *     allowed object is
     *     {@link IMODocBody.Generators }
     *     
     */
    public void setGenerators(IMODocBody.Generators value) {
        this.generators = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence maxOccurs="unbounded">
     *         &lt;element name="Generator">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="GeneratorName">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="255"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="FuelType">
     *                     &lt;simpleType>
     *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *                         &lt;minLength value="1"/>
     *                         &lt;maxLength value="15"/>
     *                       &lt;/restriction>
     *                     &lt;/simpleType>
     *                   &lt;/element>
     *                   &lt;element name="Outputs">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence maxOccurs="24">
     *                             &lt;element name="Output">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Hour" type="{http://www.theIMO.com/schema}Hour1To24"/>
     *                                       &lt;element name="EnergyMW" type="{http://www.theIMO.com/schema}MW_float" minOccurs="0"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                   &lt;element name="Capabilities">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence maxOccurs="24">
     *                             &lt;element name="Capability">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                                     &lt;sequence>
     *                                       &lt;element name="Hour" type="{http://www.theIMO.com/schema}Hour1To24"/>
     *                                       &lt;element name="EnergyMW" type="{http://www.theIMO.com/schema}MW_float"/>
     *                                     &lt;/sequence>
     *                                   &lt;/restriction>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "generator"
    })
    public static class Generators {

        @XmlElement(name = "Generator", required = true)
        protected List<IMODocBody.Generators.Generator> generator;

        /**
         * Gets the value of the generator property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the generator property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getGenerator().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link IMODocBody.Generators.Generator }
         * 
         * 
         */
        public List<IMODocBody.Generators.Generator> getGenerator() {
            if (generator == null) {
                generator = new ArrayList<IMODocBody.Generators.Generator>();
            }
            return this.generator;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="GeneratorName">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="255"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="FuelType">
         *           &lt;simpleType>
         *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
         *               &lt;minLength value="1"/>
         *               &lt;maxLength value="15"/>
         *             &lt;/restriction>
         *           &lt;/simpleType>
         *         &lt;/element>
         *         &lt;element name="Outputs">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence maxOccurs="24">
         *                   &lt;element name="Output">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Hour" type="{http://www.theIMO.com/schema}Hour1To24"/>
         *                             &lt;element name="EnergyMW" type="{http://www.theIMO.com/schema}MW_float" minOccurs="0"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *         &lt;element name="Capabilities">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence maxOccurs="24">
         *                   &lt;element name="Capability">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                           &lt;sequence>
         *                             &lt;element name="Hour" type="{http://www.theIMO.com/schema}Hour1To24"/>
         *                             &lt;element name="EnergyMW" type="{http://www.theIMO.com/schema}MW_float"/>
         *                           &lt;/sequence>
         *                         &lt;/restriction>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "generatorName",
            "fuelType",
            "outputs",
            "capabilities"
        })
        public static class Generator {

            @XmlElement(name = "GeneratorName", required = true)
            protected String generatorName;
            @XmlElement(name = "FuelType", required = true)
            protected String fuelType;
            @XmlElement(name = "Outputs", required = true)
            protected IMODocBody.Generators.Generator.Outputs outputs;
            @XmlElement(name = "Capabilities", required = true)
            protected IMODocBody.Generators.Generator.Capabilities capabilities;

            /**
             * Gets the value of the generatorName property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getGeneratorName() {
                return generatorName;
            }

            /**
             * Sets the value of the generatorName property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setGeneratorName(String value) {
                this.generatorName = value;
            }

            /**
             * Gets the value of the fuelType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getFuelType() {
                return fuelType;
            }

            /**
             * Sets the value of the fuelType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setFuelType(String value) {
                this.fuelType = value;
            }

            /**
             * Gets the value of the outputs property.
             * 
             * @return
             *     possible object is
             *     {@link IMODocBody.Generators.Generator.Outputs }
             *     
             */
            public IMODocBody.Generators.Generator.Outputs getOutputs() {
                return outputs;
            }

            /**
             * Sets the value of the outputs property.
             * 
             * @param value
             *     allowed object is
             *     {@link IMODocBody.Generators.Generator.Outputs }
             *     
             */
            public void setOutputs(IMODocBody.Generators.Generator.Outputs value) {
                this.outputs = value;
            }

            /**
             * Gets the value of the capabilities property.
             * 
             * @return
             *     possible object is
             *     {@link IMODocBody.Generators.Generator.Capabilities }
             *     
             */
            public IMODocBody.Generators.Generator.Capabilities getCapabilities() {
                return capabilities;
            }

            /**
             * Sets the value of the capabilities property.
             * 
             * @param value
             *     allowed object is
             *     {@link IMODocBody.Generators.Generator.Capabilities }
             *     
             */
            public void setCapabilities(IMODocBody.Generators.Generator.Capabilities value) {
                this.capabilities = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence maxOccurs="24">
             *         &lt;element name="Capability">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Hour" type="{http://www.theIMO.com/schema}Hour1To24"/>
             *                   &lt;element name="EnergyMW" type="{http://www.theIMO.com/schema}MW_float"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "capability"
            })
            public static class Capabilities {

                @XmlElement(name = "Capability", required = true)
                protected List<IMODocBody.Generators.Generator.Capabilities.Capability> capability;

                /**
                 * Gets the value of the capability property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the capability property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getCapability().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link IMODocBody.Generators.Generator.Capabilities.Capability }
                 * 
                 * 
                 */
                public List<IMODocBody.Generators.Generator.Capabilities.Capability> getCapability() {
                    if (capability == null) {
                        capability = new ArrayList<IMODocBody.Generators.Generator.Capabilities.Capability>();
                    }
                    return this.capability;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Hour" type="{http://www.theIMO.com/schema}Hour1To24"/>
                 *         &lt;element name="EnergyMW" type="{http://www.theIMO.com/schema}MW_float"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "hour",
                    "energyMW"
                })
                public static class Capability {

                    @XmlElement(name = "Hour")
                    protected int hour;
                    @XmlElement(name = "EnergyMW")
                    protected float energyMW;

                    /**
                     * Gets the value of the hour property.
                     * 
                     */
                    public int getHour() {
                        return hour;
                    }

                    /**
                     * Sets the value of the hour property.
                     * 
                     */
                    public void setHour(int value) {
                        this.hour = value;
                    }

                    /**
                     * Gets the value of the energyMW property.
                     * 
                     */
                    public float getEnergyMW() {
                        return energyMW;
                    }

                    /**
                     * Sets the value of the energyMW property.
                     * 
                     */
                    public void setEnergyMW(float value) {
                        this.energyMW = value;
                    }

                }

            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence maxOccurs="24">
             *         &lt;element name="Output">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *                 &lt;sequence>
             *                   &lt;element name="Hour" type="{http://www.theIMO.com/schema}Hour1To24"/>
             *                   &lt;element name="EnergyMW" type="{http://www.theIMO.com/schema}MW_float" minOccurs="0"/>
             *                 &lt;/sequence>
             *               &lt;/restriction>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "output"
            })
            public static class Outputs {

                @XmlElement(name = "Output", required = true)
                protected List<IMODocBody.Generators.Generator.Outputs.Output> output;

                /**
                 * Gets the value of the output property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the output property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getOutput().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link IMODocBody.Generators.Generator.Outputs.Output }
                 * 
                 * 
                 */
                public List<IMODocBody.Generators.Generator.Outputs.Output> getOutput() {
                    if (output == null) {
                        output = new ArrayList<IMODocBody.Generators.Generator.Outputs.Output>();
                    }
                    return this.output;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
                 *       &lt;sequence>
                 *         &lt;element name="Hour" type="{http://www.theIMO.com/schema}Hour1To24"/>
                 *         &lt;element name="EnergyMW" type="{http://www.theIMO.com/schema}MW_float" minOccurs="0"/>
                 *       &lt;/sequence>
                 *     &lt;/restriction>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "hour",
                    "energyMW"
                })
                public static class Output {

                    @XmlElement(name = "Hour")
                    protected int hour;
                    @XmlElement(name = "EnergyMW")
                    protected Float energyMW;

                    /**
                     * Gets the value of the hour property.
                     * 
                     */
                    public int getHour() {
                        return hour;
                    }

                    /**
                     * Sets the value of the hour property.
                     * 
                     */
                    public void setHour(int value) {
                        this.hour = value;
                    }

                    /**
                     * Gets the value of the energyMW property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link Float }
                     *     
                     */
                    public Float getEnergyMW() {
                        return energyMW;
                    }

                    /**
                     * Sets the value of the energyMW property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link Float }
                     *     
                     */
                    public void setEnergyMW(Float value) {
                        this.energyMW = value;
                    }

                }

            }

        }

    }

}
