//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.22 at 11:33:58 PM CST 
//


package ca.ieso.reports.schema.globaladjustment;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="TradeMonth" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="GAValues">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="FirstEstimateRate" type="{http://www.ieso.ca/schema}Money" minOccurs="0"/>
 *                   &lt;element name="SecondEstimate" type="{http://www.ieso.ca/schema}Money" minOccurs="0"/>
 *                   &lt;element name="SecondEstimateRate" type="{http://www.ieso.ca/schema}Money" minOccurs="0"/>
 *                   &lt;element name="Actual" type="{http://www.ieso.ca/schema}Money" minOccurs="0"/>
 *                   &lt;element name="ActualRate" type="{http://www.ieso.ca/schema}Money" minOccurs="0"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "tradeMonth",
    "gaValues"
})
@XmlRootElement(name = "DocBody")
public class DocBody {

    @XmlElement(name = "TradeMonth", required = true)
    protected String tradeMonth;
    @XmlElement(name = "GAValues", required = true)
    protected DocBody.GAValues gaValues;

    /**
     * Gets the value of the tradeMonth property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTradeMonth() {
        return tradeMonth;
    }

    /**
     * Sets the value of the tradeMonth property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTradeMonth(String value) {
        this.tradeMonth = value;
    }

    /**
     * Gets the value of the gaValues property.
     * 
     * @return
     *     possible object is
     *     {@link DocBody.GAValues }
     *     
     */
    public DocBody.GAValues getGAValues() {
        return gaValues;
    }

    /**
     * Sets the value of the gaValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link DocBody.GAValues }
     *     
     */
    public void setGAValues(DocBody.GAValues value) {
        this.gaValues = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="FirstEstimateRate" type="{http://www.ieso.ca/schema}Money" minOccurs="0"/>
     *         &lt;element name="SecondEstimate" type="{http://www.ieso.ca/schema}Money" minOccurs="0"/>
     *         &lt;element name="SecondEstimateRate" type="{http://www.ieso.ca/schema}Money" minOccurs="0"/>
     *         &lt;element name="Actual" type="{http://www.ieso.ca/schema}Money" minOccurs="0"/>
     *         &lt;element name="ActualRate" type="{http://www.ieso.ca/schema}Money" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "firstEstimateRate",
        "secondEstimate",
        "secondEstimateRate",
        "actual",
        "actualRate"
    })
    public static class GAValues {

        @XmlElement(name = "FirstEstimateRate")
        protected BigDecimal firstEstimateRate;
        @XmlElement(name = "SecondEstimate")
        protected BigDecimal secondEstimate;
        @XmlElement(name = "SecondEstimateRate")
        protected BigDecimal secondEstimateRate;
        @XmlElement(name = "Actual")
        protected BigDecimal actual;
        @XmlElement(name = "ActualRate")
        protected BigDecimal actualRate;

        /**
         * Gets the value of the firstEstimateRate property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getFirstEstimateRate() {
            return firstEstimateRate;
        }

        /**
         * Sets the value of the firstEstimateRate property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setFirstEstimateRate(BigDecimal value) {
            this.firstEstimateRate = value;
        }

        /**
         * Gets the value of the secondEstimate property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getSecondEstimate() {
            return secondEstimate;
        }

        /**
         * Sets the value of the secondEstimate property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setSecondEstimate(BigDecimal value) {
            this.secondEstimate = value;
        }

        /**
         * Gets the value of the secondEstimateRate property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getSecondEstimateRate() {
            return secondEstimateRate;
        }

        /**
         * Sets the value of the secondEstimateRate property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setSecondEstimateRate(BigDecimal value) {
            this.secondEstimateRate = value;
        }

        /**
         * Gets the value of the actual property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getActual() {
            return actual;
        }

        /**
         * Sets the value of the actual property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setActual(BigDecimal value) {
            this.actual = value;
        }

        /**
         * Gets the value of the actualRate property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getActualRate() {
            return actualRate;
        }

        /**
         * Sets the value of the actualRate property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setActualRate(BigDecimal value) {
            this.actualRate = value;
        }

    }

}
