//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.21 at 09:18:57 AM CST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.ieso.ca/schema", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ca.ieso.reports.schema.daintertieschedlimits;
