//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.25 at 12:17:49 PM CST 
//


package ca.ieso.reports.schema.realtimeorim;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DeliveryDate" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="DeliveryHour" type="{http://www.ieso.ca/schema}Hour1To24"/>
 *         &lt;element name="Resource" maxOccurs="unbounded">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="TiePointID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                   &lt;element name="ResourceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ResourceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                   &lt;element name="ScheduleEnergies" maxOccurs="4">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="PriceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="ScheduleEnergy" maxOccurs="2">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="ScheduleTypeID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                                       &lt;element name="IntervalEnergy" maxOccurs="12">
 *                                         &lt;complexType>
 *                                           &lt;complexContent>
 *                                             &lt;extension base="{http://www.ieso.ca/schema}IntervalEnergyValues">
 *                                               &lt;sequence>
 *                                                 &lt;element name="Flag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *                                               &lt;/sequence>
 *                                             &lt;/extension>
 *                                           &lt;/complexContent>
 *                                         &lt;/complexType>
 *                                       &lt;/element>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "deliveryDate",
    "deliveryHour",
    "resource"
})
@XmlRootElement(name = "DocBody")
public class DocBody {

    @XmlElement(name = "DeliveryDate", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar deliveryDate;
    @XmlElement(name = "DeliveryHour")
    protected int deliveryHour;
    @XmlElement(name = "Resource", required = true)
    protected List<DocBody.Resource> resource;

    /**
     * Gets the value of the deliveryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getDeliveryDate() {
        return deliveryDate;
    }

    /**
     * Sets the value of the deliveryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setDeliveryDate(XMLGregorianCalendar value) {
        this.deliveryDate = value;
    }

    /**
     * Gets the value of the deliveryHour property.
     * 
     */
    public int getDeliveryHour() {
        return deliveryHour;
    }

    /**
     * Sets the value of the deliveryHour property.
     * 
     */
    public void setDeliveryHour(int value) {
        this.deliveryHour = value;
    }

    /**
     * Gets the value of the resource property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the resource property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getResource().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DocBody.Resource }
     * 
     * 
     */
    public List<DocBody.Resource> getResource() {
        if (resource == null) {
            resource = new ArrayList<DocBody.Resource>();
        }
        return this.resource;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="TiePointID" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *         &lt;element name="ResourceName" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ResourceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *         &lt;element name="ScheduleEnergies" maxOccurs="4">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="PriceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="ScheduleEnergy" maxOccurs="2">
     *                     &lt;complexType>
     *                       &lt;complexContent>
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                           &lt;sequence>
     *                             &lt;element name="ScheduleTypeID" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                             &lt;element name="IntervalEnergy" maxOccurs="12">
     *                               &lt;complexType>
     *                                 &lt;complexContent>
     *                                   &lt;extension base="{http://www.ieso.ca/schema}IntervalEnergyValues">
     *                                     &lt;sequence>
     *                                       &lt;element name="Flag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
     *                                     &lt;/sequence>
     *                                   &lt;/extension>
     *                                 &lt;/complexContent>
     *                               &lt;/complexType>
     *                             &lt;/element>
     *                           &lt;/sequence>
     *                         &lt;/restriction>
     *                       &lt;/complexContent>
     *                     &lt;/complexType>
     *                   &lt;/element>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "tiePointID",
        "resourceName",
        "resourceType",
        "scheduleEnergies"
    })
    public static class Resource {

        @XmlElement(name = "TiePointID")
        protected String tiePointID;
        @XmlElement(name = "ResourceName", required = true)
        protected String resourceName;
        @XmlElement(name = "ResourceType", required = true)
        protected String resourceType;
        @XmlElement(name = "ScheduleEnergies", required = true)
        protected List<DocBody.Resource.ScheduleEnergies> scheduleEnergies;

        /**
         * Gets the value of the tiePointID property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTiePointID() {
            return tiePointID;
        }

        /**
         * Sets the value of the tiePointID property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTiePointID(String value) {
            this.tiePointID = value;
        }

        /**
         * Gets the value of the resourceName property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResourceName() {
            return resourceName;
        }

        /**
         * Sets the value of the resourceName property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResourceName(String value) {
            this.resourceName = value;
        }

        /**
         * Gets the value of the resourceType property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getResourceType() {
            return resourceType;
        }

        /**
         * Sets the value of the resourceType property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setResourceType(String value) {
            this.resourceType = value;
        }

        /**
         * Gets the value of the scheduleEnergies property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the scheduleEnergies property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getScheduleEnergies().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link DocBody.Resource.ScheduleEnergies }
         * 
         * 
         */
        public List<DocBody.Resource.ScheduleEnergies> getScheduleEnergies() {
            if (scheduleEnergies == null) {
                scheduleEnergies = new ArrayList<DocBody.Resource.ScheduleEnergies>();
            }
            return this.scheduleEnergies;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="PriceType" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *         &lt;element name="ScheduleEnergy" maxOccurs="2">
         *           &lt;complexType>
         *             &lt;complexContent>
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *                 &lt;sequence>
         *                   &lt;element name="ScheduleTypeID" type="{http://www.w3.org/2001/XMLSchema}string"/>
         *                   &lt;element name="IntervalEnergy" maxOccurs="12">
         *                     &lt;complexType>
         *                       &lt;complexContent>
         *                         &lt;extension base="{http://www.ieso.ca/schema}IntervalEnergyValues">
         *                           &lt;sequence>
         *                             &lt;element name="Flag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
         *                           &lt;/sequence>
         *                         &lt;/extension>
         *                       &lt;/complexContent>
         *                     &lt;/complexType>
         *                   &lt;/element>
         *                 &lt;/sequence>
         *               &lt;/restriction>
         *             &lt;/complexContent>
         *           &lt;/complexType>
         *         &lt;/element>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "priceType",
            "scheduleEnergy"
        })
        public static class ScheduleEnergies {

            @XmlElement(name = "PriceType", required = true)
            protected String priceType;
            @XmlElement(name = "ScheduleEnergy", required = true)
            protected List<DocBody.Resource.ScheduleEnergies.ScheduleEnergy> scheduleEnergy;

            /**
             * Gets the value of the priceType property.
             * 
             * @return
             *     possible object is
             *     {@link String }
             *     
             */
            public String getPriceType() {
                return priceType;
            }

            /**
             * Sets the value of the priceType property.
             * 
             * @param value
             *     allowed object is
             *     {@link String }
             *     
             */
            public void setPriceType(String value) {
                this.priceType = value;
            }

            /**
             * Gets the value of the scheduleEnergy property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the scheduleEnergy property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getScheduleEnergy().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link DocBody.Resource.ScheduleEnergies.ScheduleEnergy }
             * 
             * 
             */
            public List<DocBody.Resource.ScheduleEnergies.ScheduleEnergy> getScheduleEnergy() {
                if (scheduleEnergy == null) {
                    scheduleEnergy = new ArrayList<DocBody.Resource.ScheduleEnergies.ScheduleEnergy>();
                }
                return this.scheduleEnergy;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType>
             *   &lt;complexContent>
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
             *       &lt;sequence>
             *         &lt;element name="ScheduleTypeID" type="{http://www.w3.org/2001/XMLSchema}string"/>
             *         &lt;element name="IntervalEnergy" maxOccurs="12">
             *           &lt;complexType>
             *             &lt;complexContent>
             *               &lt;extension base="{http://www.ieso.ca/schema}IntervalEnergyValues">
             *                 &lt;sequence>
             *                   &lt;element name="Flag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
             *                 &lt;/sequence>
             *               &lt;/extension>
             *             &lt;/complexContent>
             *           &lt;/complexType>
             *         &lt;/element>
             *       &lt;/sequence>
             *     &lt;/restriction>
             *   &lt;/complexContent>
             * &lt;/complexType>
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "scheduleTypeID",
                "intervalEnergy"
            })
            public static class ScheduleEnergy {

                @XmlElement(name = "ScheduleTypeID", required = true)
                protected String scheduleTypeID;
                @XmlElement(name = "IntervalEnergy", required = true)
                protected List<DocBody.Resource.ScheduleEnergies.ScheduleEnergy.IntervalEnergy> intervalEnergy;

                /**
                 * Gets the value of the scheduleTypeID property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link String }
                 *     
                 */
                public String getScheduleTypeID() {
                    return scheduleTypeID;
                }

                /**
                 * Sets the value of the scheduleTypeID property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link String }
                 *     
                 */
                public void setScheduleTypeID(String value) {
                    this.scheduleTypeID = value;
                }

                /**
                 * Gets the value of the intervalEnergy property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the JAXB object.
                 * This is why there is not a <CODE>set</CODE> method for the intervalEnergy property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getIntervalEnergy().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link DocBody.Resource.ScheduleEnergies.ScheduleEnergy.IntervalEnergy }
                 * 
                 * 
                 */
                public List<DocBody.Resource.ScheduleEnergies.ScheduleEnergy.IntervalEnergy> getIntervalEnergy() {
                    if (intervalEnergy == null) {
                        intervalEnergy = new ArrayList<DocBody.Resource.ScheduleEnergies.ScheduleEnergy.IntervalEnergy>();
                    }
                    return this.intervalEnergy;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType>
                 *   &lt;complexContent>
                 *     &lt;extension base="{http://www.ieso.ca/schema}IntervalEnergyValues">
                 *       &lt;sequence>
                 *         &lt;element name="Flag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
                 *       &lt;/sequence>
                 *     &lt;/extension>
                 *   &lt;/complexContent>
                 * &lt;/complexType>
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "flag"
                })
                public static class IntervalEnergy
                    extends IntervalEnergyValues
                {

                    @XmlElement(name = "Flag")
                    protected String flag;

                    /**
                     * Gets the value of the flag property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getFlag() {
                        return flag;
                    }

                    /**
                     * Sets the value of the flag property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setFlag(String value) {
                        this.flag = value;
                    }

                }

            }

        }

    }

}
