//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.11.10 at 11:53:05 PM EST 
//


package com.theimo.schema;

import java.math.BigInteger;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.theimo.schema package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DocConfGroup_QNAME = new QName("http://www.theIMO.com/schema", "DocConfGroup");
    private final static QName _DocRevision_QNAME = new QName("http://www.theIMO.com/schema", "DocRevision");
    private final static QName _Hour_QNAME = new QName("http://www.theIMO.com/schema", "Hour");
    private final static QName _CreatedAt_QNAME = new QName("http://www.theIMO.com/schema", "CreatedAt");
    private final static QName _DocTitle_QNAME = new QName("http://www.theIMO.com/schema", "DocTitle");
    private final static QName _DocConfClass_QNAME = new QName("http://www.theIMO.com/schema", "DocConfClass");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.theimo.schema
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link IMODocBody }
     * 
     */
    public IMODocBody createIMODocBody() {
        return new IMODocBody();
    }

    /**
     * Create an instance of {@link IMODocBody.Generators }
     * 
     */
    public IMODocBody.Generators createIMODocBodyGenerators() {
        return new IMODocBody.Generators();
    }

    /**
     * Create an instance of {@link IMODocBody.Generators.Generator }
     * 
     */
    public IMODocBody.Generators.Generator createIMODocBodyGeneratorsGenerator() {
        return new IMODocBody.Generators.Generator();
    }

    /**
     * Create an instance of {@link IMODocBody.Generators.Generator.Capabilities }
     * 
     */
    public IMODocBody.Generators.Generator.Capabilities createIMODocBodyGeneratorsGeneratorCapabilities() {
        return new IMODocBody.Generators.Generator.Capabilities();
    }

    /**
     * Create an instance of {@link IMODocBody.Generators.Generator.Outputs }
     * 
     */
    public IMODocBody.Generators.Generator.Outputs createIMODocBodyGeneratorsGeneratorOutputs() {
        return new IMODocBody.Generators.Generator.Outputs();
    }

    /**
     * Create an instance of {@link DocConfidentiality }
     * 
     */
    public DocConfidentiality createDocConfidentiality() {
        return new DocConfidentiality();
    }

    /**
     * Create an instance of {@link DocConfGroups }
     * 
     */
    public DocConfGroups createDocConfGroups() {
        return new DocConfGroups();
    }

    /**
     * Create an instance of {@link IMODocument }
     * 
     */
    public IMODocument createIMODocument() {
        return new IMODocument();
    }

    /**
     * Create an instance of {@link IMODocHeader }
     * 
     */
    public IMODocHeader createIMODocHeader() {
        return new IMODocHeader();
    }

    /**
     * Create an instance of {@link IMODocBody.Generators.Generator.Capabilities.Capability }
     * 
     */
    public IMODocBody.Generators.Generator.Capabilities.Capability createIMODocBodyGeneratorsGeneratorCapabilitiesCapability() {
        return new IMODocBody.Generators.Generator.Capabilities.Capability();
    }

    /**
     * Create an instance of {@link IMODocBody.Generators.Generator.Outputs.Output }
     * 
     */
    public IMODocBody.Generators.Generator.Outputs.Output createIMODocBodyGeneratorsGeneratorOutputsOutput() {
        return new IMODocBody.Generators.Generator.Outputs.Output();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.theIMO.com/schema", name = "DocConfGroup")
    public JAXBElement<String> createDocConfGroup(String value) {
        return new JAXBElement<String>(_DocConfGroup_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BigInteger }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.theIMO.com/schema", name = "DocRevision")
    public JAXBElement<BigInteger> createDocRevision(BigInteger value) {
        return new JAXBElement<BigInteger>(_DocRevision_QNAME, BigInteger.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.theIMO.com/schema", name = "Hour")
    public JAXBElement<Integer> createHour(Integer value) {
        return new JAXBElement<Integer>(_Hour_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.theIMO.com/schema", name = "CreatedAt")
    public JAXBElement<XMLGregorianCalendar> createCreatedAt(XMLGregorianCalendar value) {
        return new JAXBElement<XMLGregorianCalendar>(_CreatedAt_QNAME, XMLGregorianCalendar.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.theIMO.com/schema", name = "DocTitle")
    public JAXBElement<String> createDocTitle(String value) {
        return new JAXBElement<String>(_DocTitle_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ConfidentialityClass }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.theIMO.com/schema", name = "DocConfClass")
    public JAXBElement<ConfidentialityClass> createDocConfClass(ConfidentialityClass value) {
        return new JAXBElement<ConfidentialityClass>(_DocConfClass_QNAME, ConfidentialityClass.class, null, value);
    }

}
